services:
  accounts:
    image: "ismataga/accounts:s4"
    container_name: accounts-ms
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ismataga
  loans:
    image: "ismataga/loansloans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ismataga
  cards:
    image: "ismataga/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ismataga
networks:
  ismataga:
    driver: "bridge"